name: iOS Builder

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "GitHub repository (owner/repo)"
        required: true
        default: "iRaay/Navi"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Clone Repository
        env:
          REPOSITORY: ${{ github.event.inputs.repository }}
        run: |
          git clone "https://github.com/$REPOSITORY.git" project

      - name: Install mise
        run: |
          brew install mise
          mise --version

      - name: Build iOS Scheme
        run: |
          cd project

          xcodebuild \
            -project Navi.xcodeproj \
            -scheme "Navi iOS" \
            -configuration Debug \
            -destination "generic/platform=iOS" \
            CODE_SIGNING_ALLOWED=NO \
            build
