name: iOS Builder

on:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Find Xcode Projects
        run: |
          echo "Searching..."
          find . -name "*.xcodeproj"
          find . -name "*.xcworkspace"
